Update deploy.sh
bitops-plugins/kubectl pull request #3
Opened 2022-11-03 19:52 UTC by PhillypHenning

2022-11-04 13:50 UTC, LeoDiazL commented
Code looks good.

2022-11-07 20:34 UTC, armab requested changes
Thanks for the PR! Looks like the plugin README needs an update to document this new ENV var so it's not lost in the code.

Also curious about the flow here when using `skip-deploy` vs `KUBECTL_SKIP_DEPLOY`.

2022-11-07 20:34 UTC, armab commented on deploy.sh
> +  exit 0
I see the `kubectl` doesn't have any schema like in the other plugins. Why is that?

How would this setting work then for Ansible plugin:  
```yaml
  options:
    skip-deploy: false
```

what's the flow?

2022-11-07 20:34 UTC, armab commented on deploy.sh
> +if [ "$SKIP_DEPLOY_KUBECTL" == "true" ] || [ "$KUBECTL_SKIP_DEPLOY" == "true" ]; then
Why do we need two ENV vars to control this behavior instead of one?

2022-11-10 15:33 UTC, armab approved these changes

2022-11-10 15:33 UTC, merged